class IconPath {
  IconPath._();

  static const String badge = 'assets/Icon/Badge.svg';
  static const String check = 'assets/Icon/Check.svg';
  static const String edit = 'assets/Icon/Edit.svg';
  static const String home = 'assets/Icon/Home.svg';
  static const String infoCircle = 'assets/Icon/Info-Circle.svg';
  static const String location = 'assets/Icon/Location.svg';
  static const String lock = 'assets/Icon/Lock.svg';
  static const String logout = 'assets/Icon/Logout.svg';
  static const String plus = 'assets/Icon/Plus.svg';
  static const String search = 'assets/Icon/Search.svg';
  static const String setting = 'assets/Icon/Setting.svg';
  static const String star = 'assets/Icon/Star.svg';
  static const String arrowRight = 'assets/Icon/arrow-right.svg';
  static const String arrowDown = 'assets/Icon/arrow_down.svg';
  static const String arrowUp = 'assets/Icon/arrow_up.svg';
  static const String avatarDefault = 'assets/Icon/avatar-default.svg';
  static const String back = 'assets/Icon/back.svg';
  static const String bag = 'assets/Icon/bag.svg';
  static const String clock = 'assets/Icon/clock.svg';
  static const String delete = 'assets/Icon/delete.svg';
  static const String filler = 'assets/Icon/filler.svg';
  static const String heart = 'assets/Icon/heart.svg';
  static const String logo = 'assets/Icon/logo.svg';
  static const String map = 'assets/Icon/map.svg';
  static const String menu = 'assets/Icon/menu.svg';
  static const String menu2 = 'assets/Icon/menu2.svg';
  static const String notcheck = 'assets/Icon/notcheck.svg';
  static const String point = 'assets/Icon/point.svg';
  static const String sort = 'assets/Icon/sort.svg';
  static const String sun = 'assets/Icon/sun.svg';
  static const String typeCard1 = 'assets/Icon/type_card_1.svg';
  static const String typeCard2 = 'assets/Icon/type_card_2.svg';
  static const String typeCard3 = 'assets/Icon/type_card_3.svg';
  static const String visa = 'assets/Icon/visa.svg';
  static const String voice = 'assets/Icon/voice.svg';
  static const String wallet = 'assets/Icon/wallet.svg';
}
